### Obtener todos los contenidos con sus actores, géneros y categoría
GET http://localhost:3000/contenido

### Obtener contenido por ID con sus asociaciones
GET http://localhost:3000/contenido/50

### Filtrar contenidos por título parcial o completo
GET http://localhost:3000/contenido/filter?titulo=Flash

### Filtrar contenidos por nombre de género parcial o completo
GET http://localhost:3000/contenido/filter?nombre_genero=Histo

### Filtrar contenidos por nombre de categoría parcial o completo
GET http://localhost:3000/contenido/filter?nombre_categoria=Serie

### Crear nuevo contenido
POST http://localhost:3000/contenido
Content-Type: application/json

{
    "id_categoria": 2,
    "titulo": "Mario Bros",
    "resumen": "Dos hermanos plomeros, Mario y Luigi, caen por las alcantarillas y llegan a un mundo subterráneo mágico en el que deben enfrentarse al malvado Bowser para rescatar a la princesa Peach.",
    "enlaces_trailer": "https://www.youtube.com/watch?v=_1f2RLdxQfA",
    "temporadas": 0,
    "duracion": "120 minutos",
    "generos": [1, 2, 9],
    "actores": 
    [
        { "nombre": "Chris", "apellido": "Pratt" },
        { "nombre": "Anya", "apellido": "Taylor-Joy" }
    ]
}



### Actualizar contenido por ID (Agregandole más generos y reemplazando los actores)
PUT http://localhost:3000/contenido/107
Content-Type: application/json

{
    "id_categoria": 2,
    "titulo": "Super Mario Bros 2",
    "resumen": "Dos hermanos plomeros, Mario y Luigi, caen por las alcantarillas y llegan a un mundo subterráneo mágico en el que deben enfrentarse al malvado Bowser para rescatar a la princesa Peach.",
    "enlaces_trailer": "https://www.youtube.com/watch?v=GIJIESOZALQ&ab_channel=TrailersTC",
    "temporadas": 0,
    "duracion": "105 minutos",
    "generos": [1, 2, 4, 9, 10, 11],
    "actores": [
        { "nombre": "Jack", "apellido": "Black" },
        { "nombre": "Charlie", "apellido": "Day" }
    ]
}


### Eliminar contenido por ID
DELETE http://localhost:3000/contenido/107
